### PR TITLE
fix: profile count badge

### PR DESCRIPTION
**Pull request by shivarm**

### CODE REVIEW

**Comment by shivarm** [comment]
@kaihoffman

**Comment by kaihoffman** [comment]
@shivam-sharma7 are you able to give me a bit more context on this merge? What's broken, what does it fix, what's the new source URL you list, will it remain valid, etc?

**Comment by shivarm** [comment]
> @shivam-sharma7 are you able to give me a bit more context on this merge? What's broken, what does it fix, what's the new source URL you list, will it remain valid, etc?

@kaihoffman Yes, you can see https://github.com/civo/.github/tree/master/profile/README.md the profile view count is broken and I used Shields badge to fix this problem

**Comment by kaihoffman** [comment]
> > @shivam-sharma7 are you able to give me a bit more context on this merge? What's broken, what does it fix, what's the new source URL you list, will it remain valid, etc?
> 
> @kaihoffman Yes, you can see https://github.com/civo/.github/tree/master/profile/README.md the profile view count is broken and I used Shields badge to fix this problem

Thanks for the quick reply. I've not come across the service you've tagged there. Does that not need configuring?

**Comment by shivarm** [comment]
@kaihoffman I think this will help you to merge it.
### Before
image

### After
image

**Comment by shivarm** [comment]
@kaihoffman can we merge this?

**Pull request merged**
